apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: crhm9deveastus001.azurecr.io/myapp:latest
          ports:
            - containerPort: 80
          env:
            - name: CREATOR
              value: "K8S"
      imagePullSecrets:
        - name:  myregistrykey
