apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 3833760f-f3bb-4683-8876-1c85c8769301
    keyvaultName: kv-hm8-dev-westus-002-6
    objects: |
      array:
        - |
          objectName: redis-url
          objectType: secret
          objectVersion: ""
        - |
          objectName: redis-password
          objectType: secret
          objectVersion: ""
    tenantId: "b41b72d0-4e9f-4c26-8a69-f949f367c91d"