version: '3'
services:
  web:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: sh -c "yarn install && yarn dev"